#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Digest-SHA2
version:      1.0.0
version_from: SHA2.pm
installdirs:  site
requires:
    MIME::Base64:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
